### ISSUE TITLE
Ошибка компиляции. StringUtil.cpp:331:21: error: 'now' was not declared in this scope

### ISSUE THREAD

**Issue by Bagunda** [yoreek/Arduino-GsmModem#1]
D:\Пользователи\Александр\Downloads\Arduino\ESP_CAR\test_GSM_lib\libraries\Arduino-StringUtil-master\src\StringUtil.cpp: In function 'size_t StringUtil::printOneArg(Print&, StringUtil::StringReader&, void*&)':

D:\Пользователи\Александр\Downloads\Arduino\ESP_CAR\test_GSM_lib\libraries\Arduino-StringUtil-master\src\StringUtil.cpp:262:46: error: 'year' was not declared in this scope

             n += printNum(out, year(cacheTime), '0', 0, 4);

                                              ^

D:\Пользователи\Александр\Downloads\Arduino\ESP_CAR\test_GSM_lib\libraries\Arduino-StringUtil-master\src\StringUtil.cpp:264:47: error: 'month' was not declared in this scope

             n += printNum(out, month(cacheTime), '0', 0, 2);

                                               ^

D:\Пользователи\Александр\Downloads\Arduino\ESP_CAR\test_GSM_lib\libraries\Arduino-StringUtil-master\src\StringUtil.cpp:266:45: error: 'day' was not declared in this scope

             n += printNum(out, day(cacheTime), '0', 0, 2);

                                             ^

D:\Пользователи\Александр\Downloads\Arduino\ESP_CAR\test_GSM_lib\libraries\Arduino-StringUtil-master\src\StringUtil.cpp:270:46: error: 'hour' was not declared in this scope

             n += printNum(out, hour(cacheTime), '0', 0, 2);

                                              ^

D:\Пользователи\Александр\Downloads\Arduino\ESP_CAR\test_GSM_lib\libraries\Arduino-StringUtil-master\src\StringUtil.cpp:272:48: error: 'minute' was not declared in this scope

             n += printNum(out, minute(cacheTime), '0', 0, 2);

                                                ^

D:\Пользователи\Александр\Downloads\Arduino\ESP_CAR\test_GSM_lib\libraries\Arduino-StringUtil-master\src\StringUtil.cpp:274:48: error: 'second' was not declared in this scope

             n += printNum(out, second(cacheTime), '0', 0, 2);

                                                ^

D:\Пользователи\Александр\Downloads\Arduino\ESP_CAR\test_GSM_lib\libraries\Arduino-StringUtil-master\src\StringUtil.cpp: In function 'size_t StringUtil::printf(Print&, StringUtil::StringReader&, void*&)':

D:\Пользователи\Александр\Downloads\Arduino\ESP_CAR\test_GSM_lib\libraries\Arduino-StringUtil-master\src\StringUtil.cpp:331:21: error: 'now' was not declared in this scope

     cacheTime = now();

                     ^

exit status 1
Ошибка компиляции для платы Arduino Nano.

**Comment by yoreek** [comment]
Проблема похоже в конфликте с "Time.h" из библиотеки https://github.com/PaulStoffregen/Time (эта библиотека используется в https://github.com/yoreek/Arduino-StringUtil).
Я как там советовали переделал чтобы использовался "TimeLib.h" вместо "Time.h".
Поробуй установить новую версию https://github.com/yoreek/Arduino-StringUtil.

**Comment by Bagunda** [comment]
Я не понял. Что надо сделать?
Удалил папку libraries/Time-master.
Установил заново https://github.com/PaulStoffregen/Time/archive/master.zip.
Таже ошибка

**Comment by yoreek** [comment]
Отлично.
